### ISSUE TITLE
workflow_config.py

### ISSUE THREAD

**Issue by bifidoman** [JoseBarbero/CamPype#135]
Hi

it is said:
"Set the modules you want to run in the CamPype/workflow_config.py"

there is no workflow_contig.py file

**Comment by ajcanepa** [comment]
Hi @bifidoman,
The file is at the main page see [here](https://github.com/JoseBarbero/CamPype/blob/master/campype_config.py).

**Comment by JoseBarbero** [comment]
Hi @bifidoman, we changed the file name from "workflow_config.py" to "campype_config.py" and forgot to update it in the Readme. It is fixed now. Thank you!

**Comment by JoseBarbero** [comment]
Hi @bifidoman, we changed the file name from "workflow_config.py" to "campype_config.py" and forgot to update it in the Readme. It is fixed now. Thank you!
