### ISSUE TITLE
Issue with the Report

### ISSUE THREAD

**Issue by ccalvo22** [JoseBarbero/CamPype#137]
Hi!

I have an issue with the report; after the 60% of the process of the report (long) and I don't know how to fix it: 

```
Quitting from lines 1252-1383 (CamPype_Report_long.Rmd) 
Error in `left_join()`:
! Can't join on `x$Sample` x `y$Sample` because of incompatible types.
ℹ `x$Sample` is of type <double>>.
ℹ `y$Sample` is of type <character>>.
Backtrace:
 1. AMR_matrix %>% ...
 3. dplyr:::left_join.data.frame(x = ., y = MLST %>% select(Sample, ST), by = "Sample")

Execution halted
```

Thanks

**Comment by JoseBarbero** [comment]
Hi!

Would it be possible to share the names of your samples? Maybe with that information we can find something we didn't take into account.

Maybe @ajcanepa or @ireneortega know more about this issue since they were more involved in the development of the report.

Thank you!

**Comment by ccalvo22** [comment]
Yes, sure, the sample names are numbers from 1 to 115. I also tried with other samples whose names are from "S1” to "S40”, and I found the same error.

Thank you for the pipeline is quite helpful!

**Comment by ccalvo22** [comment]
Hi, yes, the sample names are numbers from 1 to 115. Also, I tried with other samples whose names were S1 to S115, and I found the same issue.

Thank you for the pipeline!

**Comment by ireneortega** [comment]
@ccalvo22 Did you installed the workflow locally by yourself? or are you using the virtual machine?

**Comment by ajcanepa** [comment]
Hi, @ccalvo22 . 

The error message you showed from the report, says that you are trying to combine a character vector with a numeric vector in the join process, and from your last answer I can see that there are (probably) errors due to the mixing of classes in the definition of names. 

I suggest you be consistent with the names and use only numbers and/or only characters.

If you still have some problems, try to send a [`Reprex`](https://reprex.tidyverse.org/).

All the best.

**Comment by ccalvo22** [comment]
@ireneortega Locally. The test run was perfect.

**Comment by ccalvo22** [comment]
@ajcanepa, okay, I will try that. Thank you! 
I will let you know if I solve it 😉

**Comment by ireneortega** [comment]
@ccalvo22 could you please share the AMR_genes_AMRFinder_matrix.tsv file?

**Comment by ccalvo22** [comment]
@ireneortega, I will send them to you by email. 
Thank you
